### ISSUE TITLE
Container instantly fails and won't start

### ISSUE THREAD

**Issue by JulianGindi** [docker-archive-public/docker.kitematic#144]
Not sure what is causing this. I was following the tutorial on the site, and unable to ever start the container.

**Comment by patrickfree** [comment]
The latest official Ubuntu base image is also refusing to start for me (while other things like the hello-world-nginx demo and the Jenkins image are working, so it's not a general thing).

I'm getting lots of React-related warnings in the log when I open the app, if that's relevant.

When I first create the image I get this line a few times:
`[3084:0504/001535:INFO:CONSOLE(48)] "Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.", source: /Users/Patrick/Downloads/Kitematic (Beta).app/Contents/Resources/app/node_modules/react/lib/warning.js (48)`

And then when I try to run/restart the Ubuntu image:
`[3084:0504/001539:INFO:CONSOLE(219)] "[object Object]", source: /Users/Patrick/Downloads/Kitematic (Beta).app/Contents/Resources/app/build/stores/ContainerStore.js (219)`

Both of these lines also appear several times when I successfully start a Jenkins image though so I'm not sure what makes this one different.

I first installed Kitematic through Homebrew Cask and noticed this issue so to check that the issue was with Kitematic and not Cask I downloaded the app file from your website and the issue persisted.
