### ISSUE TITLE
VBox processes not killed on Quit

### ISSUE THREAD

**Issue by 1mrat** [docker-archive-public/docker.kitematic#57]
When existing Kitematic (cmd-Q or via menu), the background VBox processes are not terminated:

Screenshot from Activity Monitor:

![2014-09-05 at 19 41](https://cloud.githubusercontent.com/assets/1105579/4169881/4cf99046-352c-11e4-83f5-ecab94db180b.png)

Output from the VBox uninstall script:

```
Warning! Found the following active VirtualBox processes:
 1798   501 VBoxXPCOMIPCD
 1800   501 VBoxSVC
 1845   501 VBoxHeadless
 1848   501 VBoxNetDHCP
```

**Comment by kc8viq** [comment]
I see that this issue is closed, but I'm still experiencing this issue in the 0.5.10 beta.

Specifically, I first ran Kinematic a few days ago, started a few containers, then exited the program. Today I see, in Activity Monitor, the VBox processes.  I only noticed because VBoxHeadless was consuming 1.7 GB of RAM. The other processes are only using a few MBs. Would someone be will to re-open this issue?
![screen shot 2015-03-20 at 7 19 08 am](https://cloud.githubusercontent.com/assets/11571237/6750525/70c7d340-ced1-11e4-8b48-3121a9af07f8.png)
